#!/usr/bin/env bash
#pings an IP address passed as an argument
IP_ADDRESS=$1
if [ -z "$IP_ADDRESS" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$IP_ADDRESS"
fi