#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with while

i=0

while [ $i -le 8 ]
do
	if [[ $i -eq 8 ]] # -eq equal
	then
		echo "Hi" 
	fi
	echo "Holberton School"
	((i++))
done