#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with while

i=0

while [ $i -le 9 ]
do
	if [[ $i -eq 9 ]] # -eq equal
	then
		echo "Hi" 
	fi
	echo "Holberton School"
	((i++))
done