#!/usr/bin/env bash
# Loops from 1 to ten with bad and good luck

i=1

while ((i<=10))
do
    if [[ $i -eq 4 ]]
    then
        echo "bad luck"

    elif [[ $i -eq 8 ]]
    then
        echo "good luck"

    else
        echo "Holberton School"
    fi
    ((i++))
done