#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

hours=0
minutes=1

while [ $hours -le 12 ] #-le less or equal
do
    echo "Hour: $hours"
    while [ $minutes -le 59 ]
    do
        echo $minutes
        ((minutes++))
        done
        ((hours++))
    minutes=1
done