#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

i=1
while [ $i -le 59 ]
do
    if [ $i -eq 1 ]
    then
        echo "Hour: 0"
    fi
    echo $i
    ((i++))
done

i=1
while [ $i -le 12 ]
do
    if [ $i -eq 1 ]
    then
        echo "Hour: 1"
    fi
    echo $i
    ((i++))
done